//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToossyApp.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToossyApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://www.toossy.net:3240.
        /// </summary>
        internal static string ApiEndPoint_DEBUG {
            get {
                return ResourceManager.GetString("ApiEndPoint_DEBUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://www.toossy.net:3240.
        /// </summary>
        internal static string ApiEndPoint_RELEASE {
            get {
                return ResourceManager.GetString("ApiEndPoint_RELEASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://www.toossy.net/documents/CGU.pdf.
        /// </summary>
        internal static string DocumentEndPoint_CGU {
            get {
                return ResourceManager.GetString("DocumentEndPoint_CGU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://www.toossy.net/documents/CGV.pdf.
        /// </summary>
        internal static string DocumentEndPoint_CGV {
            get {
                return ResourceManager.GetString("DocumentEndPoint_CGV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unlimited.
        /// </summary>
        internal static string DureeDictionary_FreeLabel {
            get {
                return ResourceManager.GetString("DureeDictionary_FreeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The message added to favorite.
        /// </summary>
        internal static string FavoriteDetail_MsgRemoved {
            get {
                return ResourceManager.GetString("FavoriteDetail_MsgRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Details.
        /// </summary>
        internal static string FavoriteDetail_TitlePage {
            get {
                return ResourceManager.GetString("FavoriteDetail_TitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading....
        /// </summary>
        internal static string FavoriteList_LoadingMsg {
            get {
                return ResourceManager.GetString("FavoriteList_LoadingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Favorites.
        /// </summary>
        internal static string FavoriteList_TitlePage {
            get {
                return ResourceManager.GetString("FavoriteList_TitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All.
        /// </summary>
        internal static string Filter_All {
            get {
                return ResourceManager.GetString("Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Searching range.
        /// </summary>
        internal static string Filter_distanceHeader {
            get {
                return ResourceManager.GetString("Filter_distanceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Searching range.
        /// </summary>
        internal static string Filter_distancePicker {
            get {
                return ResourceManager.GetString("Filter_distancePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Itinerary&apos;s maximum duration.
        /// </summary>
        internal static string Filter_dureeHeader {
            get {
                return ResourceManager.GetString("Filter_dureeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum duration.
        /// </summary>
        internal static string Filter_dureePicker {
            get {
                return ResourceManager.GetString("Filter_dureePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Itinerary&apos;s language.
        /// </summary>
        internal static string Filter_langueHeader {
            get {
                return ResourceManager.GetString("Filter_langueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language(s).
        /// </summary>
        internal static string Filter_languePicker {
            get {
                return ResourceManager.GetString("Filter_languePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        internal static string Filter_None {
            get {
                return ResourceManager.GetString("Filter_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filters.
        /// </summary>
        internal static string Filter_PageTitle {
            get {
                return ResourceManager.GetString("Filter_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Itinerarys&apos; themes.
        /// </summary>
        internal static string Filter_themeHeader {
            get {
                return ResourceManager.GetString("Filter_themeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Themes.
        /// </summary>
        internal static string Filter_themePicker {
            get {
                return ResourceManager.GetString("Filter_themePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Itinerary&apos;s type.
        /// </summary>
        internal static string Filter_typeParcoursHeader {
            get {
                return ResourceManager.GetString("Filter_typeParcoursHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Itinerary&apos;s types.
        /// </summary>
        internal static string Filter_typeParcoursPicker {
            get {
                return ResourceManager.GetString("Filter_typeParcoursPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Free or paying.
        /// </summary>
        internal static string Filtre_gratuitTarifHeader {
            get {
                return ResourceManager.GetString("Filtre_gratuitTarifHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Access categories.
        /// </summary>
        internal static string Filtre_gratuitTarifPicker {
            get {
                return ResourceManager.GetString("Filtre_gratuitTarifPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minimum note.
        /// </summary>
        internal static string Filtre_noteHeader {
            get {
                return ResourceManager.GetString("Filtre_noteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minimum note.
        /// </summary>
        internal static string Filtre_notePicker {
            get {
                return ResourceManager.GetString("Filtre_notePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Free and paying.
        /// </summary>
        internal static string GratuitTarifDictionary_AllLabel {
            get {
                return ResourceManager.GetString("GratuitTarifDictionary_AllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Only free.
        /// </summary>
        internal static string GratuitTarifDictionary_FreeLabel {
            get {
                return ResourceManager.GetString("GratuitTarifDictionary_FreeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://www.toossy.net/images/.
        /// </summary>
        internal static string ImageEndPoint_DEBUG {
            get {
                return ResourceManager.GetString("ImageEndPoint_DEBUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à http://www.toossy.net/images/.
        /// </summary>
        internal static string ImageEndPoint_RELEASE {
            get {
                return ResourceManager.GetString("ImageEndPoint_RELEASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Buy.
        /// </summary>
        internal static string ItineraryDetail_Buy {
            get {
                return ResourceManager.GetString("ItineraryDetail_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paying.
        /// </summary>
        internal static string ItineraryDetail_Chargeable {
            get {
                return ResourceManager.GetString("ItineraryDetail_Chargeable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duration.
        /// </summary>
        internal static string ItineraryDetail_Duration {
            get {
                return ResourceManager.GetString("ItineraryDetail_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Free.
        /// </summary>
        internal static string ItineraryDetail_Free {
            get {
                return ResourceManager.GetString("ItineraryDetail_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading....
        /// </summary>
        internal static string ItineraryDetail_LoadingMsg {
            get {
                return ResourceManager.GetString("ItineraryDetail_LoadingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Itinerary&apos;s details.
        /// </summary>
        internal static string ItineraryDetail_PageTitle {
            get {
                return ResourceManager.GetString("ItineraryDetail_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Itinerary paid.
        /// </summary>
        internal static string ItineraryDetail_Paid {
            get {
                return ResourceManager.GetString("ItineraryDetail_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preview.
        /// </summary>
        internal static string ItineraryDetail_PreviewMenu {
            get {
                return ResourceManager.GetString("ItineraryDetail_PreviewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Price.
        /// </summary>
        internal static string ItineraryDetail_Price {
            get {
                return ResourceManager.GetString("ItineraryDetail_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Step(s).
        /// </summary>
        internal static string ItineraryDetail_Step {
            get {
                return ResourceManager.GetString("ItineraryDetail_Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Theme.
        /// </summary>
        internal static string ItineraryDetail_Theme {
            get {
                return ResourceManager.GetString("ItineraryDetail_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vote(s).
        /// </summary>
        internal static string ItineraryDetail_Vote {
            get {
                return ResourceManager.GetString("ItineraryDetail_Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Buy.
        /// </summary>
        internal static string ItineraryList_buyLabel {
            get {
                return ResourceManager.GetString("ItineraryList_buyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string ItineraryList_errorLabel {
            get {
                return ResourceManager.GetString("ItineraryList_errorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filters.
        /// </summary>
        internal static string ItineraryList_filterButton {
            get {
                return ResourceManager.GetString("ItineraryList_filterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List could not be updated, check the network.
        /// </summary>
        internal static string ItineraryList_itineraryResearchError {
            get {
                return ResourceManager.GetString("ItineraryList_itineraryResearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GPS position could not be updated, your previous position is used for the request.
        /// </summary>
        internal static string ItineraryList_localizationError {
            get {
                return ResourceManager.GetString("ItineraryList_localizationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Menu.
        /// </summary>
        internal static string ItineraryList_menuButton {
            get {
                return ResourceManager.GetString("ItineraryList_menuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Go to map.
        /// </summary>
        internal static string ItineraryList_messageButton {
            get {
                return ResourceManager.GetString("ItineraryList_messageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        internal static string ItineraryList_okLabel {
            get {
                return ResourceManager.GetString("ItineraryList_okLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application could not load your prepaid itineraries, please update the list.
        /// </summary>
        internal static string ItineraryList_paidItineraryUpdateError {
            get {
                return ResourceManager.GetString("ItineraryList_paidItineraryUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paying.
        /// </summary>
        internal static string ItineraryList_Payant {
            get {
                return ResourceManager.GetString("ItineraryList_Payant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paid.
        /// </summary>
        internal static string ItineraryList_Paye {
            get {
                return ResourceManager.GetString("ItineraryList_Paye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update.
        /// </summary>
        internal static string ItineraryList_researchLabel {
            get {
                return ResourceManager.GetString("ItineraryList_researchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Searching for itineraries.
        /// </summary>
        internal static string ItineraryList_typeOfActivity_Itinerary {
            get {
                return ResourceManager.GetString("ItineraryList_typeOfActivity_Itinerary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Localization....
        /// </summary>
        internal static string ItineraryList_typeOfActivity_Localization {
            get {
                return ResourceManager.GetString("ItineraryList_typeOfActivity_Localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Memory flushed !.
        /// </summary>
        internal static string ItineraryMenu_MemoryFlushed {
            get {
                return ResourceManager.GetString("ItineraryMenu_MemoryFlushed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Test itinerary activated.
        /// </summary>
        internal static string ItineraryMenu_TestItinerarySet {
            get {
                return ResourceManager.GetString("ItineraryMenu_TestItinerarySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Test itinerary deactivated.
        /// </summary>
        internal static string ItineraryMenu_TestItineraryUnset {
            get {
                return ResourceManager.GetString("ItineraryMenu_TestItineraryUnset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Itinerary&apos;s preview.
        /// </summary>
        internal static string ItineraryPreview_PageTitle {
            get {
                return ResourceManager.GetString("ItineraryPreview_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à See Terms and Conditions of Use.
        /// </summary>
        internal static string MentionsLegalesPage_link {
            get {
                return ResourceManager.GetString("MentionsLegalesPage_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Legal disclaimer.
        /// </summary>
        internal static string MentionsLegalesPage_PageTitle {
            get {
                return ResourceManager.GetString("MentionsLegalesPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Application Toossy is published and developed by the company Nactus Technology. By using this application, you accept the terms and conditions of use.
        /// </summary>
        internal static string MentionsLegalesPage_text {
            get {
                return ResourceManager.GetString("MentionsLegalesPage_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Menu.
        /// </summary>
        internal static string Menu_PageTitle {
            get {
                return ResourceManager.GetString("Menu_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Legal disclaimer.
        /// </summary>
        internal static string MenuPage_ConditionsAndTermsLabel {
            get {
                return ResourceManager.GetString("MenuPage_ConditionsAndTermsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Flush memory.
        /// </summary>
        internal static string MenuPage_EmptyMemory {
            get {
                return ResourceManager.GetString("MenuPage_EmptyMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Facebook.
        /// </summary>
        internal static string MenuPage_FacebookLabel {
            get {
                return ResourceManager.GetString("MenuPage_FacebookLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Favorite.
        /// </summary>
        internal static string MenuPage_FavoriteLabel {
            get {
                return ResourceManager.GetString("MenuPage_FavoriteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à De./Activate test itinerary.
        /// </summary>
        internal static string MenuPage_TestItinerary {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed arcu enim, euismod eget condimentum non, tempor ac ante. Aliquam finibus lobortis velit quis placerat. Mauris suscipit risus vitae aliquam tincidunt. Nulla facilisi. Sed justo tortor, dictum sed arcu non, euismod rutrum tellus. Mauris id lorem tortor. Integer nec purus in orci elementum sodales eu sed augue. Proin blandit, libero lobortis aliquet hendrerit, metus metus gravida magna, a imperdiet velit dui ut nisi.
        ///
        ///Sed mollis tortor blandit, int [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string MenuPage_TestItinerary_Description {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed arcu enim, euismod eget condimentum non, tempor ac ante. Aliquam finibus lobortis velit quis placerat. Mauris suscipit risus vitae aliquam tincidunt. Nulla facilisi. Sed justo tortor, dictum sed arcu non, euismod rutrum tellus. Mauris id lorem tortor. Integer nec purus in orci elementum sodales eu sed augue. Proin blandit, libero lobortis aliquet hendrerit, metus metus gravida magna, a imperdiet velit dui ut nisi.
        ///
        ///Sed mollis tortor blandit, int [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string MenuPage_TestItinerary_Description1 {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed arcu enim, euismod eget condimentum non, tempor ac ante. Aliquam finibus lobortis velit quis placerat. Mauris suscipit risus vitae aliquam tincidunt. Nulla facilisi. Sed justo tortor, dictum sed arcu non, euismod rutrum tellus. Mauris id lorem tortor. Integer nec purus in orci elementum sodales eu sed augue. Proin blandit, libero lobortis aliquet hendrerit, metus metus gravida magna, a imperdiet velit dui ut nisi.
        ///
        ///Sed mollis tortor blandit, int [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string MenuPage_TestItinerary_Description2 {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed arcu enim, euismod eget condimentum non, tempor ac ante. Aliquam finibus lobortis velit quis placerat. Mauris suscipit risus vitae aliquam tincidunt. Nulla facilisi. Sed justo tortor, dictum sed arcu non, euismod rutrum tellus. Mauris id lorem tortor. Integer nec purus in orci elementum sodales eu sed augue. Proin blandit, libero lobortis aliquet hendrerit, metus metus gravida magna, a imperdiet velit dui ut nisi.
        ///
        ///Sed mollis tortor blandit, int [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string MenuPage_TestItinerary_Description3 {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed arcu enim, euismod eget condimentum non, tempor ac ante. Aliquam finibus lobortis velit quis placerat. Mauris suscipit risus vitae aliquam tincidunt. Nulla facilisi. Sed justo tortor, dictum sed arcu non, euismod rutrum tellus. Mauris id lorem tortor. Integer nec purus in orci elementum sodales eu sed augue. Proin blandit, libero lobortis aliquet hendrerit, metus metus gravida magna, a imperdiet velit dui ut nisi.
        ///
        ///Sed mollis tortor blandit, int [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string MenuPage_TestItinerary_Description4 {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_Description4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed arcu enim, euismod eget condimentum non, tempor ac ante. Aliquam finibus lobortis velit quis placerat. Mauris suscipit risus vitae aliquam tincidunt. Nulla facilisi. Sed justo tortor, dictum sed arcu non, euismod rutrum tellus. Mauris id lorem tortor. Integer nec purus in orci elementum sodales eu sed augue. Proin blandit, libero lobortis aliquet hendrerit, metus metus gravida magna, a imperdiet velit dui ut nisi.
        ///
        ///Sed mollis tortor blandit, int [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string MenuPage_TestItinerary_Description5 {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_Description5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed arcu enim, euismod eget condimentum non, tempor ac ante. Aliquam finibus lobortis velit quis placerat. Mauris suscipit risus vitae aliquam tincidunt. Nulla facilisi. Sed justo tortor, dictum sed arcu non, euismod rutrum tellus. Mauris id lorem tortor. Integer nec purus in orci elementum sodales eu sed augue. Proin blandit, libero lobortis aliquet hendrerit, metus metus gravida magna, a imperdiet velit dui ut nisi.
        ///
        ///Sed mollis tortor blandit, int [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string MenuPage_TestItinerary_Description6 {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_Description6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed arcu enim, euismod eget condimentum non, tempor ac ante. Aliquam finibus lobortis velit quis placerat. Mauris suscipit risus vitae aliquam tincidunt. Nulla facilisi. Sed justo tortor, dictum sed arcu non, euismod rutrum tellus. Mauris id lorem tortor. Integer nec purus in orci elementum sodales eu sed augue. Proin blandit, libero lobortis aliquet hendrerit, metus metus gravida magna, a imperdiet velit dui ut nisi.
        ///
        ///Sed mollis tortor blandit, int [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string MenuPage_TestItinerary_Description7 {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_Description7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Example 1.
        /// </summary>
        internal static string MenuPage_TestItinerary_Example1 {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_Example1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Example 2.
        /// </summary>
        internal static string MenuPage_TestItinerary_Example2 {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_Example2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Example 3.
        /// </summary>
        internal static string MenuPage_TestItinerary_Example3 {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_Example3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Example 4.
        /// </summary>
        internal static string MenuPage_TestItinerary_Example4 {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_Example4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Example 5.
        /// </summary>
        internal static string MenuPage_TestItinerary_Example5 {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_Example5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Example 6.
        /// </summary>
        internal static string MenuPage_TestItinerary_Example6 {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_Example6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Example 7.
        /// </summary>
        internal static string MenuPage_TestItinerary_Example7 {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_Example7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ville.
        /// </summary>
        internal static string MenuPage_TestItinerary_IllustrationsTite {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_IllustrationsTite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à City.
        /// </summary>
        internal static string MenuPage_TestItinerary_IllustrationsTitel {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_IllustrationsTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ancienne Manufacture.
        /// </summary>
        internal static string MenuPage_TestItinerary_IllustrationsTitel1 {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_IllustrationsTitel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bar Typique.
        /// </summary>
        internal static string MenuPage_TestItinerary_IllustrationsTitel2 {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_IllustrationsTitel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exemple Collection Musée.
        /// </summary>
        internal static string MenuPage_TestItinerary_IllustrationsTitel3 {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_IllustrationsTitel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gravure Historique.
        /// </summary>
        internal static string MenuPage_TestItinerary_IllustrationsTitel4 {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_IllustrationsTitel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Histoire Du Patrimoine.
        /// </summary>
        internal static string MenuPage_TestItinerary_IllustrationsTitel5 {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_IllustrationsTitel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spécialité Locale.
        /// </summary>
        internal static string MenuPage_TestItinerary_IllustrationsTitel6 {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_IllustrationsTitel6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Travail Du Verre.
        /// </summary>
        internal static string MenuPage_TestItinerary_IllustrationsTitel7 {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_IllustrationsTitel7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Test itinerary.
        /// </summary>
        internal static string MenuPage_TestItinerary_Titel {
            get {
                return ResourceManager.GetString("MenuPage_TestItinerary_Titel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lire le tutoriel.
        /// </summary>
        internal static string MenuPage_TutorialLabel {
            get {
                return ResourceManager.GetString("MenuPage_TutorialLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Twitter.
        /// </summary>
        internal static string MenuPage_TwitterLabel {
            get {
                return ResourceManager.GetString("MenuPage_TwitterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading....
        /// </summary>
        internal static string MessageDetail_LoadingMsg {
            get {
                return ResourceManager.GetString("MessageDetail_LoadingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message saved to favorite.
        /// </summary>
        internal static string MessageDetail_MsgAdded {
            get {
                return ResourceManager.GetString("MessageDetail_MsgAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message&apos;s details.
        /// </summary>
        internal static string MessageDetail_PageTitle {
            get {
                return ResourceManager.GetString("MessageDetail_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information.
        /// </summary>
        internal static string MessageMap_InformationLabel {
            get {
                return ResourceManager.GetString("MessageMap_InformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string MessageMap_mapPreloadingFail {
            get {
                return ResourceManager.GetString("MessageMap_mapPreloadingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string MessageMap_mapPreloadingSuccess {
            get {
                return ResourceManager.GetString("MessageMap_mapPreloadingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All messages could not be loaded, check the network.
        /// </summary>
        internal static string MessageMap_msgPreloadingFail {
            get {
                return ResourceManager.GetString("MessageMap_msgPreloadingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All the steps are preloaded, the map will now be downloaded, it may take a little while..
        /// </summary>
        internal static string MessageMap_msgPreloadingSuccess {
            get {
                return ResourceManager.GetString("MessageMap_msgPreloadingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You selected none itinerary.
        /// </summary>
        internal static string MessageMap_noneItinerarySelected {
            get {
                return ResourceManager.GetString("MessageMap_noneItinerarySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        internal static string MessageMap_okLabel {
            get {
                return ResourceManager.GetString("MessageMap_okLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Step&apos;s map.
        /// </summary>
        internal static string MessageMap_PageTitle {
            get {
                return ResourceManager.GetString("MessageMap_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning.
        /// </summary>
        internal static string MessageMap_WarningLabel {
            get {
                return ResourceManager.GetString("MessageMap_WarningLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please accet the terms and conditions of use.
        /// </summary>
        internal static string PayPage_approvalProblem {
            get {
                return ResourceManager.GetString("PayPage_approvalProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Buy itinerary.
        /// </summary>
        internal static string PayPage_buyButtonText {
            get {
                return ResourceManager.GetString("PayPage_buyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CVV.
        /// </summary>
        internal static string PayPage_cardCvcLabel {
            get {
                return ResourceManager.GetString("PayPage_cardCvcLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XXX.
        /// </summary>
        internal static string PayPage_cardCvcPlaceHolder {
            get {
                return ResourceManager.GetString("PayPage_cardCvcPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expire in.
        /// </summary>
        internal static string PayPage_cardDateLabel {
            get {
                return ResourceManager.GetString("PayPage_cardDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MM/YY.
        /// </summary>
        internal static string PayPage_cardDatePlaceHolder {
            get {
                return ResourceManager.GetString("PayPage_cardDatePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Associated name.
        /// </summary>
        internal static string PayPage_cardHolderLabel {
            get {
                return ResourceManager.GetString("PayPage_cardHolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à e.g.: Dupond.
        /// </summary>
        internal static string PayPage_cardHolderPlaceHolder {
            get {
                return ResourceManager.GetString("PayPage_cardHolderPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Card&apos;s number.
        /// </summary>
        internal static string PayPage_cardNumberLabel {
            get {
                return ResourceManager.GetString("PayPage_cardNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XXXX XXXX XXXX XXXX.
        /// </summary>
        internal static string PayPage_cardNumberPlaceHolder {
            get {
                return ResourceManager.GetString("PayPage_cardNumberPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I have read and agreed to the Conditions of Sales.
        /// </summary>
        internal static string PayPage_cgvApproval {
            get {
                return ResourceManager.GetString("PayPage_cgvApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string PayPage_dataAnApprovalProblem {
            get {
                return ResourceManager.GetString("PayPage_dataAnApprovalProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string PayPage_dataProblem {
            get {
                return ResourceManager.GetString("PayPage_dataProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to forget this card ?.
        /// </summary>
        internal static string PayPage_DeleteCard {
            get {
                return ResourceManager.GetString("PayPage_DeleteCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forget the card.
        /// </summary>
        internal static string PayPage_ForgetCard {
            get {
                return ResourceManager.GetString("PayPage_ForgetCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        internal static string PayPage_itineraryEmailLabel {
            get {
                return ResourceManager.GetString("PayPage_itineraryEmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter your email.
        /// </summary>
        internal static string PayPage_itineraryEmailPlaceholder {
            get {
                return ResourceManager.GetString("PayPage_itineraryEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Itinerary&apos;s titel.
        /// </summary>
        internal static string PayPage_itineraryTitle {
            get {
                return ResourceManager.GetString("PayPage_itineraryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à See  General Conditions of Sales.
        /// </summary>
        internal static string PayPage_link_CGV {
            get {
                return ResourceManager.GetString("PayPage_link_CGV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Purchase the itinerary.
        /// </summary>
        internal static string PayPage_PageTitle {
            get {
                return ResourceManager.GetString("PayPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paiement failed, please try again.
        /// </summary>
        internal static string PayPage_paymentFailed {
            get {
                return ResourceManager.GetString("PayPage_paymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paiement succeeded, you can follow the itinerary.
        /// </summary>
        internal static string PayPage_paymentSuceeded {
            get {
                return ResourceManager.GetString("PayPage_paymentSuceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à excluding VAT.
        /// </summary>
        internal static string PayPage_priceHtLabel {
            get {
                return ResourceManager.GetString("PayPage_priceHtLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à including VAT.
        /// </summary>
        internal static string PayPage_priceTtcLabel {
            get {
                return ResourceManager.GetString("PayPage_priceTtcLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save my datas.
        /// </summary>
        internal static string PayPage_rememberData {
            get {
                return ResourceManager.GetString("PayPage_rememberData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à VAT.
        /// </summary>
        internal static string PayPage_tvaLabel {
            get {
                return ResourceManager.GetString("PayPage_tvaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string RatingPage_mainLabelText {
            get {
                return ResourceManager.GetString("RatingPage_mainLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rating.
        /// </summary>
        internal static string RatingPage_noteLabelText {
            get {
                return ResourceManager.GetString("RatingPage_noteLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Give your feedback !.
        /// </summary>
        internal static string RatingPage_PageTitle {
            get {
                return ResourceManager.GetString("RatingPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Send.
        /// </summary>
        internal static string RatingPage_submitButton {
            get {
                return ResourceManager.GetString("RatingPage_submitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your comment will be sent to the itinerary&apos;s administrator.
        /// </summary>
        internal static string ReportPage_mainLabelText {
            get {
                return ResourceManager.GetString("ReportPage_mainLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Report Abuses.
        /// </summary>
        internal static string ReportPage_PageTitle {
            get {
                return ResourceManager.GetString("ReportPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Report abuses.
        /// </summary>
        internal static string ReportPage_ReportLabel {
            get {
                return ResourceManager.GetString("ReportPage_ReportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string TestItinerary_Msg {
            get {
                return ResourceManager.GetString("TestItinerary_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string TestItinerary_MsgType {
            get {
                return ResourceManager.GetString("TestItinerary_MsgType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Architecture.
        /// </summary>
        internal static string ThemeDictionary_ArchitectureLabel {
            get {
                return ResourceManager.GetString("ThemeDictionary_ArchitectureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à History.
        /// </summary>
        internal static string ThemeDictionary_HistoryLabel {
            get {
                return ResourceManager.GetString("ThemeDictionary_HistoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Leasure.
        /// </summary>
        internal static string ThemeDictionary_LeisureLabel {
            get {
                return ResourceManager.GetString("ThemeDictionary_LeisureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Autres.
        /// </summary>
        internal static string ThemeDictionary_Others {
            get {
                return ResourceManager.GetString("ThemeDictionary_Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parc.
        /// </summary>
        internal static string ThemeDictionary_ParkLabel {
            get {
                return ResourceManager.GetString("ThemeDictionary_ParkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Street Art.
        /// </summary>
        internal static string ThemeDictionary_StreetArt {
            get {
                return ResourceManager.GetString("ThemeDictionary_StreetArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Urbanism.
        /// </summary>
        internal static string ThemeDictionary_UrbanismLabel {
            get {
                return ResourceManager.GetString("ThemeDictionary_UrbanismLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string Tutorial_text_1 {
            get {
                return ResourceManager.GetString("Tutorial_text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string Tutorial_text_10 {
            get {
                return ResourceManager.GetString("Tutorial_text_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string Tutorial_text_11 {
            get {
                return ResourceManager.GetString("Tutorial_text_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string Tutorial_text_12 {
            get {
                return ResourceManager.GetString("Tutorial_text_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string Tutorial_text_13 {
            get {
                return ResourceManager.GetString("Tutorial_text_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string Tutorial_text_14 {
            get {
                return ResourceManager.GetString("Tutorial_text_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string Tutorial_text_2 {
            get {
                return ResourceManager.GetString("Tutorial_text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string Tutorial_text_3 {
            get {
                return ResourceManager.GetString("Tutorial_text_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string Tutorial_text_4 {
            get {
                return ResourceManager.GetString("Tutorial_text_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string Tutorial_text_5 {
            get {
                return ResourceManager.GetString("Tutorial_text_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string Tutorial_text_6 {
            get {
                return ResourceManager.GetString("Tutorial_text_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string Tutorial_text_7 {
            get {
                return ResourceManager.GetString("Tutorial_text_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string Tutorial_text_8 {
            get {
                return ResourceManager.GetString("Tutorial_text_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string Tutorial_text_9 {
            get {
                return ResourceManager.GetString("Tutorial_text_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string TutorialPage_PageTitle {
            get {
                return ResourceManager.GetString("TutorialPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tour.
        /// </summary>
        internal static string TypeParcoursDictionary_TourLabel {
            get {
                return ResourceManager.GetString("TypeParcoursDictionary_TourLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Walk.
        /// </summary>
        internal static string TypeParcoursDictionary_WalkLabel {
            get {
                return ResourceManager.GetString("TypeParcoursDictionary_WalkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
